# Generated by Django 4.0.6 on 2023-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('current_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('specialisation', models.CharField(choices=[('AI', 'Artificial Intellignce & Data Science'), ('CS', 'Cyber Security'), ('DA', 'Data Administration'), ('GD', 'Graphic Design'), ('HO', 'Hardware & Operating Systems'), ('IS', 'Information Systems'), ('NC', 'Network Configuration'), ('SD', 'Software Development')], max_length=50)),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=50)),
            ],
        ),
    ]
