# Generated by Django 4.0.6 on 2023-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectidea',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
