# Generated by Django 4.0.6 on 2023-05-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_projectidea_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectidea',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projectidea',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
