# Generated by Django 4.0.6 on 2023-06-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_student_project_wishlist'),
        ('progress', '0003_alter_projectidea_description_alter_projectidea_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300, null=True)),
                ('git_link', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('C', 'Complete')], default='O', max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('current_step', models.IntegerField(default=1)),
                ('steps', models.JSONField(default=list)),
                ('project_idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.projectidea')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
