# Generated by Django 4.0.6 on 2023-06-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_studentproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='git_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
