# Generated by Django 4.0.6 on 2023-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_studentproject_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='current_step',
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
