# Generated by Django 4.0.6 on 2023-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_remove_studentproject_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('specialisation', models.CharField(choices=[('AI', 'Artificial Intellignce & Data Science'), ('CS', 'Cyber Security'), ('DA', 'Data Administration'), ('GD', 'Graphic Design'), ('HO', 'Hardware & Operating Systems'), ('IS', 'Information Systems'), ('NC', 'Network Configuration'), ('SD', 'Software Development')], max_length=50, null=True)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectidea',
            name='specialisation',
        ),
    ]
