# Generated by Django 4.1.2 on 2023-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_img', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=800)),
                ('header_img', models.CharField(max_length=800)),
                ('publication', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('isOnline', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=800)),
                ('img', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=200)),
                ('organiser', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('format', models.JSONField(default=list)),
                ('themes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TechJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=800)),
                ('job_logo', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=200)),
                ('posted', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('areas', models.JSONField(default=list)),
            ],
        ),
    ]
