# Generated by Django 4.1.2 on 2023-04-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('isOnline', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=800)),
                ('img', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('format', models.JSONField(default=list)),
                ('themes', models.JSONField(default=list)),
            ],
        ),
    ]
