# Generated by Django 4.1.2 on 2023-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_techevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
