# Generated by Django 4.1.2 on 2023-04-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_techevent_organiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=800)),
                ('job_logo', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=200)),
                ('posted', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('areas', models.JSONField(default=list)),
            ],
        ),
    ]
