# Generated by Django 4.1.2 on 2023-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('user_token', models.CharField(max_length=200, null=True)),
                ('last_active', models.CharField(max_length=200, null=True)),
                ('reset_key', models.CharField(max_length=200, null=True)),
                ('news_history', models.JSONField(default=list, null=True)),
            ],
        ),
    ]
