# Generated by Django 4.1.2 on 2023-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
