# Generated by Django 4.1.2 on 2023-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reset_key',
        ),
        migrations.AddField(
            model_name='student',
            name='reset_otp',
            field=models.IntegerField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reset_time',
            field=models.DateTimeField(null=True),
        ),
    ]
