# Generated by Django 4.1.2 on 2023-05-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('UoN', 'University of Nairobi'), ('CUEA', 'Catholic University of East Africa'), ('KU', 'Kenyatta University'), ('JKUAT', 'Jomo Kenyatta University'), ('STRATH', 'Strathmore University')], max_length=50)),
                ('current_sem', models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('2.0', '2.0'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2')], max_length=50)),
                ('current_avg', models.FloatField(default=0.0)),
                ('current_honours', models.CharField(choices=[('First Class', 'First Class'), ('Second Upper', 'Second Upper'), ('Second Lower', 'Second Lower'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('cs01', models.FloatField(default=0.0)),
                ('cs02', models.FloatField(default=0.0)),
                ('cs03', models.FloatField(default=0.0)),
                ('cs04', models.FloatField(default=0.0)),
                ('cs05', models.FloatField(default=0.0)),
                ('cs06', models.FloatField(default=0.0)),
                ('cs07', models.FloatField(default=0.0)),
                ('cs08', models.FloatField(default=0.0)),
                ('cs09', models.FloatField(default=0.0)),
                ('cs10', models.FloatField(default=0.0)),
                ('cs11', models.FloatField(default=0.0)),
                ('cs12', models.FloatField(default=0.0)),
                ('cs13', models.FloatField(default=0.0)),
                ('cs14', models.FloatField(default=0.0)),
                ('cs15', models.FloatField(default=0.0)),
                ('cs16', models.FloatField(default=0.0)),
                ('cs17', models.FloatField(default=0.0)),
                ('cs18', models.FloatField(default=0.0)),
                ('student_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('UoN', 'University of Nairobi'), ('CUEA', 'Catholic University of East Africa'), ('KU', 'Kenyatta University'), ('JKUAT', 'Jomo Kenyatta University'), ('STRATH', 'Strathmore University')], max_length=50)),
                ('semester', models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('2.0', '2.0'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.0', '4.0'), ('4.1', '4.1'), ('4.2', '4.2')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('elective', models.BooleanField(default=False)),
                ('elective_group', models.CharField(max_length=50, null=True)),
                ('grouping_name', models.JSONField(default=list)),
                ('grouping_code', models.JSONField(default=list)),
                ('unit_perc', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('mark', models.FloatField(default=0.0)),
                ('ac_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.academicprofile')),
                ('school_unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.schoolunit')),
            ],
        ),
    ]
