# Generated by Django 4.1.2 on 2023-05-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_academicprofile_schoolunit_studentunit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolGrouping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("UoN", "University of Nairobi"),
                            ("CUEA", "Catholic University of East Africa"),
                            ("KU", "Kenyatta University"),
                            ("JKUAT", "Jomo Kenyatta University"),
                            ("STRATH", "Strathmore University"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("unit_percentage", models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name="schoolunit",
            old_name="unit_perc",
            new_name="unit_percentages",
        ),
        migrations.RemoveField(
            model_name="academicprofile",
            name="school",
        ),
        migrations.RemoveField(
            model_name="studentunit",
            name="mark",
        ),
        migrations.AddField(
            model_name="schoolunit",
            name="grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schoolunit",
            name="mark",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="academicprofile",
            name="current_honours",
            field=models.CharField(
                choices=[
                    ("First Class", "First Class"),
                    ("Second Upper", "Second Upper"),
                    ("Second Lower", "Second Lower"),
                    ("Pass", "Pass"),
                    ("Fail", "Fail"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="academicprofile",
            name="current_sem",
            field=models.FloatField(
                choices=[
                    (1.0, 1.0),
                    (1.1, 1.1),
                    (1.2, 1.2),
                    (2.0, 2.0),
                    (2.1, 2.1),
                    (2.2, 2.2),
                    (3.0, 3.0),
                    (3.1, 3.1),
                    (3.2, 3.2),
                    (4.0, 4.0),
                    (4.1, 4.1),
                    (4.2, 4.2),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schoolunit",
            name="semester",
            field=models.FloatField(
                choices=[
                    (1.0, 1.0),
                    (1.1, 1.1),
                    (1.2, 1.2),
                    (2.0, 2.0),
                    (2.1, 2.1),
                    (2.2, 2.2),
                    (3.0, 3.0),
                    (3.1, 3.1),
                    (3.2, 3.2),
                    (4.0, 4.0),
                    (4.1, 4.1),
                    (4.2, 4.2),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="studentunit",
            name="grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                max_length=1,
                null=True,
            ),
        ),
    ]
