# Generated by Django 4.1.2 on 2023-05-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_schoolgrouping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_username', models.CharField(max_length=50)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_prs', models.IntegerField(default=0)),
                ('total_stars', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_contribs', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('c', models.FloatField(default=0.0)),
                ('cPlusPlus', models.FloatField(default=0.0)),
                ('java', models.FloatField(default=0.0)),
                ('javascript', models.FloatField(default=0.0)),
                ('python', models.FloatField(default=0.0)),
                ('r', models.FloatField(default=0.0)),
                ('jupyter', models.FloatField(default=0.0)),
                ('dart', models.FloatField(default=0.0)),
                ('kotlin', models.FloatField(default=0.0)),
                ('go', models.FloatField(default=0.0)),
                ('swift', models.FloatField(default=0.0)),
                ('cSharp', models.FloatField(default=0.0)),
                ('typescript', models.FloatField(default=0.0)),
                ('php', models.FloatField(default=0.0)),
                ('objective_c', models.FloatField(default=0.0)),
                ('ruby', models.FloatField(default=0.0)),
                ('html', models.FloatField(default=0.0)),
                ('css', models.FloatField(default=0.0)),
                ('sql', models.FloatField(default=0.0)),
                ('rust', models.FloatField(default=0.0)),
                ('student_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
