# Generated by Django 4.1.2 on 2023-04-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_reset_time_student_reset_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TechnicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_username', models.CharField(max_length=50)),
                ('total_commits', models.IntegerField(default=0)),
                ('totals_prs', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('top_languages', models.JSONField(default=[])),
                ('repos', models.JSONField(default=[])),
                ('technical_score', models.FloatField(default=0.0)),
                ('specialisation_rank', models.JSONField(default=[])),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
