# Generated by Django 4.1.2 on 2023-04-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_email_technicalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalprofile',
            name='repos',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='specialisation_rank',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='technicalprofile',
            name='top_languages',
            field=models.JSONField(default=dict),
        ),
    ]
