# Generated by Django 4.1.2 on 2023-05-07 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_technicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internships_no', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('ai_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('cs_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('da_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('gd_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('ho_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('is_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('na_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('sd_industry', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('student_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('location_type', models.CharField(choices=[('Online', 'Online'), ('Hybrid', 'Hybrid'), ('On-Site', 'On-Site')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('time_spent', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=dict)),
                ('wx_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.workexpprofile')),
            ],
        ),
    ]
