# Generated by Django 4.1.2 on 2023-05-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprofile",
            name="cs01",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs02",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs03",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs04",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs05",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs06",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs07",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs08",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs09",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs10",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs11",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs12",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs13",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs14",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs15",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs16",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs17",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="academicprofile",
            name="cs18",
            field=models.FloatField(default=0.0),
        ),
    ]
