# Generated by Django 4.1.2 on 2023-04-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_technicalprofile_repos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalprofile',
            old_name='totals_prs',
            new_name='total_prs',
        ),
    ]
