# Generated by Django 4.1.2 on 2023-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_schoolunit_elective_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolunit",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="schoolunit",
            name="school",
            field=models.CharField(
                choices=[
                    ("UoN", "University of Nairobi"),
                    ("CUEA", "Catholic University of East Africa"),
                    ("KU", "Kenyatta University"),
                    ("JKUAT", "Jomo Kenyatta University"),
                    ("STRATH", "Strathmore University"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="schoolunit",
            name="semester",
            field=models.FloatField(
                choices=[
                    (1.0, 1.0),
                    (1.1, 1.1),
                    (1.2, 1.2),
                    (2.0, 2.0),
                    (2.1, 2.1),
                    (2.2, 2.2),
                    (3.0, 3.0),
                    (3.1, 3.1),
                    (3.2, 3.2),
                    (4.0, 4.0),
                    (4.1, 4.1),
                    (4.2, 4.2),
                ]
            ),
        ),
    ]
