# Generated by Django 4.1.2 on 2023-04-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_workexpprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexpprofile',
            name='skills',
            field=models.JSONField(default=dict),
        ),
    ]
