# Generated by Django 4.1.2 on 2023-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_workexpprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexpprofile',
            name='specialisation_rank',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workexpprofile',
            name='work_exp_score',
            field=models.FloatField(default=0.0),
        ),
    ]
