# Generated by Django 4.1.2 on 2023-04-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_workexpprofile_specialisation_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=dict)),
                ('mbti', models.CharField(max_length=6, null=True)),
                ('soft_skill_score', models.FloatField(default=0.0)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
