# Generated by Django 4.1.2 on 2023-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_academicprofile_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolgrouping",
            name="code",
            field=models.CharField(default="cs0", max_length=5),
            preserve_default=False,
        ),
    ]
