# Generated by Django 4.1.2 on 2023-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_schoolgrouping_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="industry",
            field=models.CharField(
                choices=[
                    ("sd_industry", "Software Development"),
                    ("na_industry", "Networking"),
                    ("ai_industry", "Data Science & AI"),
                    ("cs_industry", "Cyber Security"),
                    ("da_industry", "Database Administration"),
                    ("ho_industry", "Hardware & Operating Systems"),
                    ("is_industry", "Information Systems"),
                    ("gd_industry", "Graphics & Design"),
                ],
                default="sd_industry",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
