# Generated by Django 4.1.2 on 2023-04-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_softskillprofile_mbti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexpprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='workexpprofile',
            name='title',
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship')], max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('Online', 'Online'), ('Hybrid', 'Hybrid'), ('On-Site', 'On-Site')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('industry', models.CharField(choices=[('Software Development', 'Software Development'), ('Networking', 'Networking'), ('Data Science & AI', 'Data Science & AI'), ('Cyber Security', 'Cyber Security'), ('Database Administration', 'Database Administration'), ('IT & Support', 'IT & Support'), ('Mobile Development', 'Mobile Development'), ('Web Development', 'Web Development'), ('Design', 'Design')], max_length=100)),
                ('skills', models.JSONField(default=dict)),
                ('wx_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.workexpprofile')),
            ],
        ),
    ]
