# Generated by Django 4.1.2 on 2023-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_workexperience_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalprofile",
            name="c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="cPlusPlus",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="cSharp",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="css",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="dart",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="go",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="html",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="javascript",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="jupyter",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="kotlin",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="objective_c",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="php",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="python",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="r",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="ruby",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="rust",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="sql",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="swift",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="typescript",
            field=models.FloatField(default=0.0),
        ),
    ]
