# Generated by Django 4.1.2 on 2023-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0012_technicalprofile_c_technicalprofile_cplusplus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalprofile",
            name="aspNet",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="cmake",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="technicalprofile",
            name="scss",
            field=models.FloatField(default=0.0),
        ),
    ]
