# Generated by Django 4.1.2 on 2023-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0013_technicalprofile_aspnet_technicalprofile_cmake_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="specialisation",
            field=models.CharField(
                choices=[
                    ("AI", "Artificial Intellignce & Data Science"),
                    ("CS", "Cyber Security"),
                    ("DA", "Data Administration"),
                    ("GD", "Graphic Design"),
                    ("HO", "Hardware & Operating Systems"),
                    ("IS", "Information Systems"),
                    ("NC", "Network Configuration"),
                    ("SD", "Software Development"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
