# Generated by Django 4.0.6 on 2023-05-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_childhod_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentunit',
            name='school_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.schoolunit'),
        ),
    ]
