# Generated by Django 4.0.6 on 2023-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_student_project_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spec_roadmaps',
            field=models.JSONField(default=list),
        ),
    ]
